POST http://localhost:4002/api/tasks/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Task assigned to Johndiddles200",
  "description": "The description of a task assigned to Johndiddles200",
  "priority": "LOW",
  "dueDate": "2026-05-28",
  "status": "TODO"
}

