POST http://localhost:4002/api/auth/register
Content-Type: application/json

{
  "username": "Johndiddles205",
  "email": "john205@email.com",
  "password": "Password@123"
}


> {% client.global.set("token", response.body.token) %}