POST http://localhost:4002/api/tasks/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Self Assigned task",
  "description": "The description of a self assigned task",
  "priority": "HIGH",
  "dueDate": "2026-05-28",
  "status": "TODO"
}

